testing json

diff --git a/.github/workflows/mcp_unit_test.yml b/.github/workflows/mcp_unit_test.yml
--- a/.github/workflows/mcp_unit_test.yml
+++ b/.github/workflows/mcp_unit_test.yml
@@ -38,21 +38,25 @@ jobs:
 
     - name: Run unit tests
       run: |
-        EXIT_CODE=0
-        MESSAGE="PASSED: All unit tests passed"
-        for dir in $(find $(pwd) \( -not -path "$(pwd)/module_import/*" \) -and \( -type f -name 'main.tf' \) |  sed -r 's|/[^/]+$||'); do
-          echo "Directory: ${dir}"
-          cd $dir
-          terraform init
-          terraform apply -auto-approve
-          for value in $(terraform output -json | jq -c '.[].value'); do 
-            result=$(echo -n "$value" | jq -r '.result')
-            if [ "$result" != pass ]
-            then
-              MESSAGE="FAIL: There are failed unit tests"
-              EXIT_CODE=222
-            fi
-          done
-        done
-        echo $MESSAGE
-        exit $EXIT_CODE
+        cd cloudrun
+        terraform init
+        terraform apply -auto-approve
+        cat terraform output-json
+#        EXIT_CODE=0
+#        MESSAGE="PASSED: All unit tests passed"
+#        for dir in $(find $(pwd) \( -not -path "$(pwd)/module_import/*" \) -and \( -type f -name 'main.tf' \) |  sed -r 's|/[^/]+$||'); do
+#          echo "Directory: ${dir}"
+#          cd $dir
+#          terraform init
+#          terraform apply -auto-approve
+#          for value in $(terraform output -json | jq -c '.[].value'); do
+#            result=$(echo -n "$value" | jq -r '.result')
+#            if [ "$result" != pass ]
+#            then
+#              MESSAGE="FAIL: There are failed unit tests"
+#              EXIT_CODE=222
+#            fi
+#          done
+#        done
+#        echo $MESSAGE
+#        exit $EXIT_CODE
